version: '3'
services:
  app:
    restart: always 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: app
    tty: true
    entrypoint: npm run start
    networks:
      - app-sql
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: postgres-db
    ports:
      - '5432:5432'
    networks:
      - app-sql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: checkout
    tty: true
    expose:
      - 5432
networks:
  app-sql:
    driver: bridge
