version: '3'

services:
  app:
    restart: always 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: app
    tty: true
    entrypoint: npm run start